
// online bot cfg
module.exports = {
    botName: 'RIRIKA',
    botID: '1266703631697182801',
    discordToken: process.env.DISCORD_1266703631697182801_BOTTOKEN,
    clientSecret: process.env.DISCORD_1266703631697182801_SECRET,
    resonance: 'こんりり',
    plugins: [
        'messageLogger',
        'spamBotKicker',
        'streamStartTime',
        'twitterAntiFilter',
        'welcomeMsg',
        // 'delall',
        // 'delMsgByMenu',
        // 'dlimg',
        // 'dlsitebot',
        // 'eval',
        // 'fxtwitter',
        // 'hook',
        // 'ip',
        // 'memberCounter',
        // 'permissionSwitch',
        // 'reactionVote',
        // 'reboot',
        // 'reportThread',
        // 'rssbot',
        // 'search',
        // 'superChat',
        // 'uptimer',
        // 'verifyThread',
    ],
}
