# fly.toml app configuration file generated for arraydcbot on 2024-03-02T14:08:12+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'arraydcbot'
primary_region = 'hkg'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[env]
  HOST_TYPE = 'FLY_IO'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
