
// online bot cfg
module.exports = {
    botName: 'BANPEN',
    botID: '1253617427095359550',
    discordToken: process.env.DISCORD_1253617427095359550_BOTTOKEN,
    clientSecret: process.env.DISCORD_1253617427095359550_SECRET,
    resonance: 'ぶんぶん',
    plugins: [
        'memberChecker5',
        'messageLogger',
        'reportThread',
        'spamBotKicker',
        'streamStartTime',
        'twitterAntiFilter',
        'welcomeMsg',
        // 'delall',
        // 'delMsgByMenu',
        // 'dlimg',
        // 'dlsitebot',
        // 'eval',
        // 'fxtwitter',
        // 'hook',
        // 'ip',
        // 'memberCounter',
        // 'permissionSwitch',
        // 'reactionVote',
        // 'reboot',
        // 'rssbot',
        // 'search',
        // 'superChat',
        // 'uptimer',
        // 'verifyThread',
    ],
}
