
// online bot cfg
module.exports = {
    botName: 'OTOSE',
    botID: '1179344721047474207',
    discordToken: process.env.DISCORD_1179344721047474207_BOTTOKEN,
    clientSecret: process.env.DISCORD_1179344721047474207_SECRET,
    resonance: 'こけこっこ',
    plugins: [
        'spamBotKicker',
        'streamStartTime',
        'twitterAntiFilter',
        // 'delall',
        // 'delMsgByMenu',
        // 'dlimg',
        // 'dlsitebot',
        // 'eval',
        // 'fxtwitter',
        // 'hook',
        // 'ip',
        // 'memberCounter',
        // 'messageLogger',
        // 'permissionSwitch',
        // 'reactionVote',
        // 'reboot',
        // 'reportThread',
        // 'rssbot',
        // 'search',
        // 'superChat',
        // 'uptimer',
        // 'verifyThread',
        // 'welcomeMsg',
    ],
}
