
// online bot cfg
module.exports = {
    botName: 'DLsite',
    botID: '920485085935984641',
    discordToken: process.env.DISCORD_920485085935984641_BOTTOKEN,
    clientSecret: null,
    resonance: 'ぬる',
    plugins: [
        'delall',
        // 'delMsgByMenu',
        'dlimg',
        'dlsitebot',
        'eval',
        // 'fxtwitter',
        // 'hook',
        'ip',
        // 'memberCounter',
        // 'messageLogger',
        // 'permissionSwitch',
        // 'reactionVote',
        'reboot',
        // 'reportThread',
        'rssbot',
        // 'search',
        'spamBotKicker',
        'streamStartTime',
        // 'superChat',
        // 'twitterAntiFilter',
        // 'uptimer',
        // 'verifyThread',
        // 'welcomeMsg',
    ],
}