
// online bot cfg
module.exports = {
    botName: 'DLsite',
    botID: '920485085935984641',
    discordToken: process.env.DISCORD_920485085935984641_BOTTOKEN,
    clientSecret: null,
    resonance: 'ぬる',
    plugins: [
        'eval',
        'delall',
        'dlimg',
        'dlsitebot',
        'fxtwitter',
        // 'hook',
        'ip',
        'memberChecker4',
        // 'memberCounter',
        // 'messageLogger',
        // 'ping',
        // 'reactionRole',
        // 'reactionVote',
        'reboot',
        // 'reportThread',
        'rssbot',
        'spamBotKicker',
        'streamStartTime',
        // 'superChat',
        // 'timeTag2',
        'twitterAntiFilter',
        'twitterListener3',
        // 'uptimer',
        'verifyThread',
        // 'welcomeMsg',
    ],
}
