
// online bot cfg
module.exports = {
    botName: 'SSRB',
    botID: '713624995372466179',
    discordToken: process.env.DISCORD_713624995372466179_BOTTOKEN,
    clientSecret: process.env.DISCORD_713624995372466179_SECRET,
    resonance: 'ぼた',
    plugins: [
        'delMsgByMenu',
        'fxtwitter',
        'hook',
        'ip',
        'memberChecker5',
        'memberCounter',
        'messageLogger',
        'permissionSwitch',
        'reactionVote',
        'reportThread',
        'search',
        'spamBotKicker',
        'streamStartTime',
        'superChat',
        'twitterAntiFilter',
        'verifyThread',
        'welcomeMsg',
        // 'delall',
        // 'dlimg',
        // 'dlsitebot',
        // 'eval',
        // 'reboot',
        // 'rssbot',
        // 'uptimer',
    ],
}
