
// online bot cfg
module.exports = {
    botName: 'POKOBE',
    botID: '928492714482343997',
    discordToken: process.env.DISCORD_928492714482343997_BOTTOKEN,
    clientSecret: process.env.DISCORD_928492714482343997_SECRET,
    resonance: 'ジャキン',
    plugins: [
        // 'delall',
        'fxtwitter',
        // 'hook',
        'memberChecker4',
        // 'memberCounter',
        // 'messageLogger',
        // 'ping',
        // 'reactionRole',
        // 'reactionVote',
        // 'reboot',
        // 'reportThread',
        // 'rssbot',
        'spamBotKicker',
        'streamStartTime',
        // 'superChat',
        'twitterAntiFilter',
        // 'twitterListener3',
        // 'uptimer',
        // 'verifyThread',
        // 'welcomeMsg',
    ],
}
