
// online bot cfg
module.exports = {
    botName: 'POKOBE',
    botID: '928492714482343997',
    discordToken: process.env.DISCORD_928492714482343997_BOTTOKEN,
    clientSecret: process.env.DISCORD_928492714482343997_SECRET,
    resonance: 'ジャキン',
    plugins: [
        'fxtwitter',
        'memberChecker5',
        'spamBotKicker',
        'streamStartTime',
        'twitterAntiFilter',
        // 'delall',
        // 'delMsgByMenu',
        // 'dlimg',
        // 'dlsitebot',
        // 'eval',
        // 'hook',
        // 'ip',
        // 'memberCounter',
        // 'messageLogger',
        // 'permissionSwitch',
        // 'reactionVote',
        // 'reboot',
        // 'reportThread',
        // 'rssbot',
        // 'search',
        // 'superChat',
        // 'uptimer',
        // 'verifyThread',
        // 'welcomeMsg',
    ],
}
