name: Fly Deploy
on: 
  push:
    branches:
      - main

  schedule:
    - cron: '0 4 1 * *'

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Shutdown server
      #   uses: superfly/flyctl-actions@master
      #   with:
      #     args: "scale count 0 -a arraydcbot"

      - name: Deploy
        uses: superfly/flyctl-actions@master
        with:
          args: "deploy --detach"

      # - name: Start up
      #   uses: superfly/flyctl-actions@master
      #   with:
      #     args: "scale count 1 -a arraydcbot"
      
